sonar.projectKey=UMan-Beings_UManitobaGuessr

# Scan both backend and frontend source code
sonar.sources=backend/src/main,web/src
sonar.java.binaries=backend/build/classes/java/main

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/gradle/**,docs/**

sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
