# Use OpenJDK 21 as base image
FROM eclipse-temurin:21-jre-alpine

# All relative paths below are now relative to /app (working directory inside the container)
WORKDIR /app

# Copy the already-built Spring Boot JAR into the container
COPY build/libs/umg-0.0.1-SNAPSHOT.jar app.jar

# Start application
CMD ["java", "-jar", "app.jar"]
