/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameConfiguration: typeof import('./components/GameConfiguration.vue')['default']
    GameStats: typeof import('./components/GameStats.vue')['default']
    GuessMap: typeof import('./components/GuessMap.vue')['default']
    GuessResult: typeof import('./components/GuessResult.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroBanner: typeof import('./components/HeroBanner.vue')['default']
    HomeLinkLogo: typeof import('./components/HomeLinkLogo.vue')['default']
    RevealMap: typeof import('./components/RevealMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatItem: typeof import('./components/StatItem.vue')['default']
    UserStats: typeof import('./components/UserStats.vue')['default']
  }
}
